name: dashboard_env
channels:
  - conda-forge
  - defaults
dependencies:
  - asgiref
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - azure-core-cpp
  - azure-storage-blobs-cpp
  - azure-storage-common-cpp
  - blosc
  - branca
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cfitsio
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - colorama
  - contourpy
  - cycler
  - django
  - expat
  - fiona
  - fmt
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - freexl
  - gdal
  - geoalchemy2
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - greenlet
  - hdf4
  - hdf5
  - icu
  - idna
  - intel-openmp
  - jinja2
  - joblib
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libabseil
  - libaec
  - libarchive
  - libblas
  - libboost-headers
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libdeflate
  - libexpat
  - libffi
  - libgdal
  - libglib
  - libgoogle-cloud
  - libgoogle-cloud-storage
  - libgrpc
  - libiconv
  - libjpeg-turbo
  - libkml
  - liblapack
  - libnetcdf
  - libpng
  - libpq
  - libprotobuf
  - libre2-11
  - librttopo
  - libspatialindex
  - libspatialite
  - libsqlite
  - libssh2
  - libtiff
  - libwebp-base
  - libxml2
  - libzip
  - libzlib
  - lz4-c
  - mapclassify
  - markupsafe
  - matplotlib-base
  - minizip
  - mkl
  - munkres
  - networkx
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pcre2
  - pillow
  - pip
  - pixman
  - poppler
  - poppler-data
  - postgresql
  - proj
  - psycopg2
  - pyparsing
  - pyproj
  - pysocks
  - python
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytz
  - re2
  - requests
  - rtree
  - scikit-learn
  - scipy
  - setuptools
  - shapely
  - six
  - snappy
  - spdlog
  - sqlalchemy
  - sqlite
  - sqlparse
  - tbb
  - threadpoolctl
  - tiledb
  - tk
  - typing-extensions
  - typing_extensions
  - tzdata
  - uriparser
  - urllib3
  - wheel
  - xerces-c
  - xorg-libxau
  - xorg-libxdmcp
  - xyzservices
  - xz
  - zlib
  - zstd
  - pip:
      - django-cors-headers
      - django-environ
      - django-redis
      - future
      - geoserver-rest
      - geoserver-restconfig
      - gisdata
      - pygments
      - redis
      - seaborn
      - xmltodict
      - whitenoise
      - gunicorn
