# Generated by Django 5.0.4 on 2024-05-04 00:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geojson', '0006_alter_bus_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedGeneratorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('country', models.CharField(max_length=255)),
                ('geographic_name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('p_nom_max', models.FloatField()),
                ('weight', models.FloatField()),
                ('p_nom', models.FloatField()),
                ('capital_cost', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('p_nom_min', models.FloatField()),
                ('marginal_cost', models.FloatField()),
                ('bus', models.CharField(max_length=255)),
                ('p_nom_extendable', models.BooleanField()),
                ('carrier', models.CharField(max_length=255)),
                ('control', models.CharField(max_length=255)),
                ('p_nom_opt', models.FloatField()),
                ('sign', models.IntegerField()),
                ('build_year', models.IntegerField()),
                ('min_up_time', models.IntegerField()),
                ('min_down_time', models.IntegerField()),
                ('up_time_before', models.IntegerField()),
                ('down_time_before', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('p_min_pu', models.FloatField()),
                ('p_max_pu', models.FloatField()),
                ('p_set', models.FloatField()),
                ('q_set', models.FloatField()),
                ('marginal_cost_quadratic', models.FloatField()),
                ('lifetime', models.FloatField()),
                ('committable', models.BooleanField()),
                ('start_up_cost', models.FloatField()),
                ('shut_down_cost', models.FloatField()),
                ('ramp_limit_up', models.FloatField()),
                ('ramp_limit_down', models.FloatField()),
                ('ramp_limit_start_up', models.FloatField()),
                ('ramp_limit_shut_down', models.FloatField()),
                ('cf', models.FloatField()),
                ('crt', models.FloatField()),
                ('usdpt', models.FloatField()),
            ],
            options={
                'db_table': 'combined_generator_data_co',
                'managed': False,
            },
        ),
    ]
